(use xlsxwriterscm)

(create-workbook "array-formula.xlsx")
(add-worksheet "")
(set-pos 0 1)
(worksheet-write-number 500)
(set-pos 1 1)
(worksheet-write-number 10)
(set-pos 4 1)
(worksheet-write-number 1)
(set-pos 5 1)
(worksheet-write-number 2)
(set-pos 6 1)
(worksheet-write-number 3)
(set-pos 0 2)
(worksheet-write-number 300)
(set-pos 1 2)
(worksheet-write-number 15)
(set-pos 4 2)
(worksheet-write-number 20234)
(set-pos 5 2)
(worksheet-write-number 21003)
(set-pos 6 2)
(worksheet-write-number 10000)
(worksheet-write-array-formula "{=SUM(B1:C1*B2:C2)}" 0 0 0 0)
(worksheet-write-array-formula "{=SUM(B1:C1*B2:C2)}" 1 0 1 0)
(worksheet-write-array-formula "{=TREND(C5:C7, B5:B7)}" 4 0 6 0)
(close-workbook)
(exit)

