(use xlsxwriterscm)

(create-workbook "chart-bar-example.xlsx")
(add-worksheet "")
(define (write-worksheet-data)
  (let ((d `((2 40 30)
             (2 40 25)
             (4 50 30)
             (5 30 10)
             (6 25 5)
             (7 50 10)))
        (row 1))
    (worksheet-write-string "Number")
    (set-col 1)
    (worksheet-write-string "Batch 1")
    (set-col 2)
    (worksheet-write-string "Batch 2")
    (for-each
     (lambda(x)
       (set-pos row 0)
       (worksheet-write-number (car x))
       (set-col 1)
       (worksheet-write-number (cadr x))
       (set-col 2)
       (worksheet-write-number (caddr x))
       (set! row (add1 row)))
     d)))

(write-worksheet-data)
(create-chart ($chart-type 'bar))
(create-chart-series "=Sheet1!$A$2:$A$7" "=Sheet1!$B$2:$B$7")
(chart-series-set-name "=Sheet1!$B$1")
(create-chart-series "=Sheet1!$A$2:$A$7" "=Sheet1!$C$2:$C$7")
(chart-series-set-name "=Sheet1!$C$1")
(chart-title-set-name "Results of sample analysis")
(chart-x-axis-set-name "Test number")
(chart-y-axis-set-name "Sample length (mm)")
(chart-set-style 11)
(set-pos 1 4)
(worksheet-insert-chart)

(add-worksheet "")
(set-pos 0 0)
(write-worksheet-data)
(create-chart ($chart-type 'bar-stacked))
(create-chart-series "=Sheet2!$A$2:$A$7" "=Sheet2!$B$2:$B$7")
(chart-series-set-name "=Sheet2!$B$1")
(create-chart-series "=Sheet2!$A$2:$A$7" "=Sheet2!$C$2:$C$7")
(chart-series-set-name "=Sheet2!$C$1")
(chart-title-set-name "Results of sample analysis")
(chart-x-axis-set-name "Test number")
(chart-y-axis-set-name "Sample length (mm)")
(chart-set-style 11)
(set-pos 1 4)
(worksheet-insert-chart)

(add-worksheet "")
(set-pos 0 0)
(write-worksheet-data)
(create-chart ($chart-type 'bar-stacked-percent))
(create-chart-series "=Sheet3!$A$2:$A$7" "=Sheet3!$B$2:$B$7")
(chart-series-set-name "=Sheet3!$B$1")
(create-chart-series "=Sheet3!$A$2:$A$7" "=Sheet3!$C$2:$C$7")
(chart-series-set-name "=Sheet3!$C$1")
(chart-title-set-name "Results of sample analysis")
(chart-x-axis-set-name "Test number")
(chart-y-axis-set-name "Sample length (mm)")
(chart-set-style 11)
(set-pos 1 4)
(worksheet-insert-chart)

(close-workbook)
(exit)

