(use xlsxwriterscm)

(create-workbook-constant-memory "constant-memory.xlsx")
(add-worksheet "")
(let ((max-row 1000)
      (max-col 50))
  (define (iter-row row-num)
    (print "1")
    (when (< row-num max-row)
      (print "2")
      (define (iter-col col-num)
        (print "3")
        (when (< col-num max-col)
          (print "4")
          (set-pos row-num col-num)
          (worksheet-write-number 1234.5)
          (iter-col (add1 col-num))))
      (iter-col 0)
      (iter-row (add1 row-num))))
  (iter-row 0))
(close-workbook)
(exit)

