(use xlsxwriterscm)
(define (write-worksheet-data)
  (set-format 'format)
  (set-pos 0 0)
  (worksheet-write-string "some examples of data validation in libxlsxwriter.")
  (set-pos 0 3)
  (worksheet-write-string "sample data.")
  (set-format 'none)
  (set-pos 2 3)
  (worksheet-write-string "Integers.")
  (set-col 4)
  (worksheet-write-number 1)
  (set-col 5)
  (worksheet-write-number 10)
  (set-pos 3 3)
  (worksheet-write-string "List Data")
  (set-col 4)
  (worksheet-write-string "open")
  (set-col 5)
  (worksheet-write-string "high")
  (set-col 6)
  (worksheet-write-string "close")
  (set-pos 4 3)
  (worksheet-write-string "Formula")
  (set-col 4)
  (worksheet-write-formula "=AND(F5=50,G5=60)")
  (set-col 5)
  (worksheet-write-number 50)
  (set-col 6)
  (worksheet-write-number 60))

(create-workbook "data-validations.xlsx"  )
(add-worksheet "")
(define-formats '((format ((set-border ($border 'thin))
                           (set-fg-color #xC6EFCE)
                           (set-bold)
                           (turn-on-text-wrap)
                           (set-align ($align 'vertical-center))
                           (set-indent 1)))
                  (none ())))
(worksheet-set-column 55 0 0)
(worksheet-set-column 15 1 1)
(worksheet-set-column 15 3 3)
(worksheet-set-row 36 0)
(write-worksheet-data)

(set-pos 2 0)
(worksheet-write-string "Enter an integer between 1 and 10.")
(set-validation-validate ($validation-type 'integer))
(set-validation-criteria ($validation-criteria 'between))
(set-validation-min-number 1)
(set-validation-max-number 10)
(set-col 1)
(create-data-validation)

(set-pos 4 0)
(worksheet-write-string "Enter an integer not between 1 and 10 (using cell references)")
(set-validation-validate ($validation-type 'integer-formula))
(set-validation-criteria ($validation-criteria 'not-between))
(set-validation-min-formula "=E3")
(set-validation-max-formula "=F3")
(set-col 1)
(create-data-validation)

(set-pos 6 0)
(worksheet-write-string "Enter an integer greater than 0")
(set-validation-validate ($validation-type 'integer))
(set-validation-criteria ($validation-criteria 'greater-than))
(set-validation-value-number 0)
(set-col 1)
(create-data-validation)

(set-pos 8 0)
(worksheet-write-string "Enter an integer less than 10")
(set-validation-validate ($validation-type 'integer))
(set-validation-criteria ($validation-criteria 'less-than))
(set-validation-value-number 10)
(set-col 1)
(create-data-validation)

(set-pos 10 0)
(worksheet-write-string "Enter a decimal between 0.1 and 0.5")
(set-validation-validate ($validation-type 'decimal))
(set-validation-criteria ($validation-criteria 'between))
(set-validation-min-number 0.1)
(set-validation-min-number 0.5)
(set-col 1)
(create-data-validation)

(set-pos 10 0)
(worksheet-write-string "Select a value from a drop down list")
(set-validation-validate ($validation-type 'list))
(create-data-validation-list-entry "open")
(create-data-validation-list-entry "high")
(create-data-validation-list-entry "close")
(set-validation-value-list)
(set-col 1)
(create-data-validation)

(set-pos 12 0)
(worksheet-write-string "Select a value from a drop down list (using a cell range)")
(set-validation-validate ($validation-type 'list-formula))
(set-validation-value-formula "=$E$4:$G$4")
(set-validation-value-list)
(set-col 1)
(create-data-validation)

(set-pos 14 0)
(worksheet-write-string "Enter a date between 1/1/2008 and 12/12/2008")
(set-validation-validate ($validation-type 'date))
(set-validation-criteria ($validation-criteria 'between))
(set-validation-min-date-time 2008 1 1 0 0 0)
(set-validation-max-date-time 2008 12 12 0 0 0)
(set-col 1)
(create-data-validation)

(set-pos 16 0)
(worksheet-write-string  "Enter a time between 6:00 and 12:00")
(set-validation-validate ($validation-type 'date))
(set-validation-criteria ($validation-criteria 'between))
(set-validation-min-date-time 0 0 0 6 0 0)
(set-validation-max-date-time 0 0 0 12 0 0)
(set-col 1)
(create-data-validation)

(set-pos 18 0)
(worksheet-write-string  "Enter a string longer than 3 characters")
(set-validation-validate ($validation-type 'length))
(set-validation-criteria ($validation-criteria 'greater-than))
(set-validation-value-number 3)
(set-col 1)
(create-data-validation)

(set-pos 20 0)
(worksheet-write-string  "Enter a value if the following is true \"=AND(F5=50,G5=60)\"")
(set-validation-validate ($validation-type 'custom-formula))
(set-validation-value-formula "=AND(F5=50,G5=60)")
(set-col 1)
(create-data-validation)

(set-pos 22 0)
(worksheet-write-string  "Displays a message when you select the cell")
(set-validation-validate ($validation-type 'integer))
(set-validation-criteria ($validation-criteria 'between))
(set-validation-min-number 1)
(set-validation-max-number 100)
(set-validation-input-title "Enter an integer")
(set-validation-input-message "between 1 and 100")
(set-col 1)
(create-data-validation)

(set-pos 24 0)
(worksheet-write-string "Display a custom error message when integer is between 1 and 100")
(set-validation-validate ($validation-type 'integer))
(set-validation-criteria ($validation-criteria 'between))
(set-validation-min-number 1)
(set-validation-max-number 100)
(set-validation-input-title "Enter an integer")
(set-validation-input-message "between 1 and 100")
(set-validation-error-title "Input value is not valid!")
(set-validation-error-message "It should be an integer between 1 and 100")
(set-validation-error-type ($validation-error-type 'information))
(set-col 1)
(create-data-validation)

(close-workbook)
(exit)


