(use xlsxwriterscm)

(create-workbook "define-name.xlsx")
(add-worksheet "")
(add-worksheet "")
(workbook-define-name "Sales"         "=!G1:H10")
(workbook-define-name "Exchange_rate" "=0.96")
(all-worksheets-set-column 45 0 0)
(all-worksheets-write-string "This worksheet contains some defined names.")
(set-row 1)
(all-worksheets-write-string "See Formulas -> Name Manager above.")
(set-row 2)
(all-worksheets-write-string "Example formula in cell B3 ->")
(set-pos 2 1)
(all-worksheets-write-formula  "=Exchange_rate")
(close-workbook)
(exit)
