(use xlsxwriterscm)


;simple example
(create-workbook "headers-footers.xlsx")
(add-worksheet "Simple")
(worksheet-set-header "&CHere is some centered text")
(worksheet-set-footer "&LHere is some left aligned text")
(worksheet-set-column 50 0 0)
(set-pos 0 0)
(worksheet-write-string "Select print preview to see header and footer")
(add-to-row-number-list 20)
(add-to-row-number-list 0)
(worksheet-set-h-page-breaks)

(add-worksheet "Variables")
(worksheet-set-header "&LPage &P of &N&CFilename: &F&RSheetname: &A")
(worksheet-set-footer "&LCurrent date: &D&RCurrent time: &T")
(worksheet-set-column 50 0 0)
(set-pos 0 0)
(worksheet-write-string "Select print preview to see header and footer")
(add-to-row-number-list 20)
(add-to-row-number-list 0)
(worksheet-set-h-page-breaks)
(set-pos 20 0)
(worksheet-write-string "Next page")

(add-worksheet "Mixed Fonts")
(worksheet-set-header "&C&\"Courier New,Bold\"Hello &\"Arial,Italic\"World")
(worksheet-set-footer "&C&\"Symbol\"e&\"Arial\" = mc&X2")
(worksheet-set-column 50 0 0)
(set-pos 0 0)
(worksheet-write-string "Select print preview to see header and footer")

(add-worksheet "Word wrap")
(worksheet-set-header "&CHeading 1\nHeading 2")
(worksheet-set-column 50 0 0)
(set-pos 0 0)
(worksheet-write-string "Select print preview to see header and footer")

(add-worksheet "Ampersand")
(worksheet-set-header "&CCuriouser && Curiouser - Attorneys at Law")
(worksheet-set-column 50 0 0)
(set-pos 0 0)
(worksheet-write-string "Select print preview to see header and footer")
(set-pos 20 0)

(close-workbook)
(exit)
