(use xlsxwriterscm)

(create-workbook "hyperlinks.xlsx")
(add-worksheet "")
(init-formats 2)
(create-format)
(set-underline-single)
(set-font-color #x0000FF)
(create-format)
(set-underline-single)
(set-font-color #xFF0000)
(worksheet-set-column 30 0 0)
(set-pos 0 0)
(set-format-index 0)
(worksheet-write-url "http://libxlsxwriter.github.io")
(set-pos 2 0)
(worksheet-write-url "http://libxlsxwriter.github.io")
(set-format-index 1)
(worksheet-write-string "Read the documentation")
(set-pos 4 0)
(worksheet-write-url "http://libxlsxwriter.github.io")
(set-pos 6 0)
(set-format-index 0)
(worksheet-write-url "mailto:foo@bar.org")
(set-pos 8 0)
(worksheet-write-url "mailto:foo@bar.org")
(worksheet-write-string "Drop me a line.")
(close-workbook)
(exit)

