(use xlsxwriterscm)

(create-workbook "merge-range.xlsx")
(add-worksheet "")
(define-formats '((none ())
                  (merge-format ((set-align ($align 'center))
                                 (set-align ($align 'vertical-center))
                                 (set-bold)
                                 (set-bg-color #xFFFA03)
                                 (set-border ($border 'thin))))))
(set-format 'none)
(worksheet-set-column 12 1 3)
(worksheet-set-row 30 3)
(worksheet-set-row 30 6)
(worksheet-set-row 30 7)
(set-pos 3 1)
(set-format 'merge-format)
(worksheet-merge-range "Merged Range" 3 1 3 3)
(worksheet-merge-range "Merged Range" 6 1 7 3)
(close-workbook)
(exit)
