(use xlsxwriterscm)

(initFormats 2222)
(createWorkbook "test21.xlsx")
(addWorksheet "foo worksheet")
(setRow 1)
(setCol 1)
(createFormat)
(setPattern ($pattern 'dark-trellis))
(setFontColor #xFFFFFF)
(worksheetWriteString "bar")
(addWorksheet "asdf..")
(setPos 2 2)
(createFormat)
(setBold)
(setItalic)
(worksheetWriteString "zap")
(createFormat)
(setPos 2 3)
(setShrink)
(setBold)
(setFontName "Avenir Black Oblique")
(setFontColor #xFF0000)
(setPattern ($pattern 'solid))
(setBGColor #x00FF00)
(setFGColor #xABCDEF)
(worksheetWriteString "bell")
(createFormat)
(setPos 2 4)
(setRotation 40)
(setFontName "Avenir Black Oblique")
(worksheetWriteString "bam")
(createFormat)
(worksheetSetColumn 22 0 5)
(createFormat)
(worksheetInsertImage "i.jpg" 5 5)
(worksheetInsertImageOpt 10 10 .025 .150 "i.jpg" 0 0)
(setPos 20 0)
(createFormat)
(setPattern ($pattern 'light-down))
(setBGColor #x00FF00)
(setFGColor #xABCDEF)
(setBorderColor #x00FFF8)
(setBorder ($border 'hair))
(worksheetWriteString "shazam")
(createFormat)
(setPos 21 0)
(worksheetWriteString "no format")
(createFormat)
(setPos 22 0)
(setRotation 90)
(worksheetWriteString "??")
(setPos 23 0)
(setFormatIndex 1)
(worksheetWriteString "!!")
(setPos 24 0)
(worksheetWriteNumber 12345.344)
(setFormatIndex 3)
(setAlign  ($align 'right))
(setBorderTop ($border 'dashed))
(closeWorkbook)
(print "check out test21.xlsx")


(exit)
