(use xlsxwriterscm)

(init-formats 2222)
(create-workbook "test21.xlsx")
(add-worksheet "foo worksheet")
(set-row 1)
(set-col 1)
(create-format)
(set-pattern ($pattern 'dark-trellis))
(set-font-color #xFFFFFF)
(worksheet-write-string "bar")
(add-worksheet "asdf..")
(set-pos 2 2)
(create-format)
(set-bold)
(set-italic)
(worksheet-write-string "zap")
(create-format)
(set-pos 2 3)
(set-shrink)
(set-bold)
(set-font-name "Avenir Black Oblique")
(set-font-color #xFF0000)
(set-pattern ($pattern 'solid))
(set-bg-color #x00FF00)
(set-fg-color #xABCDEF)
(worksheet-write-string "bell")
(create-format)
(set-pos 2 4)
(set-rotation 40)
(set-font-name "Avenir Black Oblique")
(worksheet-write-string "bam")
(create-format)
(worksheet-set-column 22 0 5)
(create-format)
(worksheet-insert-image "i.jpg" 5 5)
(worksheet-insert-image-opt 10 10 .025 .150 "i.jpg" 0 0)
(set-pos 20 0)
(create-format)
(set-pattern ($pattern 'light-down))
(set-bg-color #x00FF00)
(set-fg-color #xABCDEF)
(set-border-color #x00FFF8)
(set-border ($border 'hair))
(worksheet-write-string "shazam")
(create-format)
(set-pos 21 0)
(worksheet-write-string "no format")
(create-format)
(set-pos 22 0)
(set-rotation 90)
(worksheet-write-string "??")
(set-pos 23 0)
(set-format-index 1)
(worksheet-write-string "!!")
(set-pos 24 0)
(worksheet-write-number 12345.344)
(set-format-index 3)
(set-align  ($align 'right))
(set-border-top ($border 'dashed))
(close-workbook)
(print "check out test21.xlsx")


(exit)
