(use xlsxwriterscm)

(define expenses '((Rent . 1000)
                   (Gas  . 100)
                   (Food . 300)
                   (Gym  . 50)))
(define row 0)
(define col 0)

(create-workbook "tut1.xlsx")
(add-worksheet "")
(define (write-expenses e)
  (set-pos row col)
  (if (not (null? e))
      (let* ((curr-row (car e))
             (curr-str (symbol->string (car curr-row)))
             (curr-num (cdr curr-row)))
        (worksheet-write-string curr-str)
        (set-col (add1 col))
        (worksheet-write-number curr-num)
        (set! row (add1 row))
        (write-expenses (cdr e)))
      (begin (worksheet-write-string "TOTAL")
             (set-col (add1 col))
             (worksheet-write-formula "=SUM(B1:B4)"))))
(write-expenses expenses)
(close-workbook)
(exit)
