(use xlsxwriterscm)

(define expenses '((Rent . 1000)
                   (Gas  . 100)
                   (Food . 300)
                   (Gym  . 50)))
(define row 0)
(define col 0)

(create-workbook "tut2.xlsx")
(add-worksheet "")
(init-formats 2)
(create-format)
(set-bold)
(create-format)
(set-cell-num-format "$#,##0")
(set-format-index 0)
(worksheet-write-string "Item")
(set-col (add1 col))
(worksheet-write-string "Cost")
(set! row (add1 row))
(set-format-index 1)
(define (write-expenses e)
  (set-pos row col)
  (if (not (null? e))
      (let* ((curr-row (car e))
             (curr-str (symbol->string (car curr-row)))
             (curr-num (cdr curr-row)))
        (worksheet-write-string curr-str)
        (set-col (add1 col))
        (worksheet-write-number curr-num)
        (set! row (add1 row))
        (write-expenses (cdr e)))
      (begin (worksheet-write-string "TOTAL")
             (set-col (add1 col))
             (worksheet-write-formula "=SUM(B1:B4)"))))
(write-expenses expenses)
(close-workbook)
(exit)
